[package]
org = "mohamedsabthar"
name = "loader"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "mohamedsabthar"
name = "dataloader"
version = "0.1.0"
repository="local"